### NUMPY

#### Un array es una lista de listas.

In [1]:
import numpy as np

In [2]:
#puedes hacer un array con términos random

a = np.random.random((10,4))
print(a)

[[0.55903238 0.44005495 0.64622466 0.33556072]
 [0.92668281 0.38309836 0.89968563 0.78781461]
 [0.86255717 0.99951959 0.18851202 0.50664423]
 [0.78436947 0.84122982 0.18650833 0.7935121 ]
 [0.65441089 0.77557341 0.77911722 0.51566277]
 [0.4628121  0.34730139 0.20339765 0.37120356]
 [0.94443712 0.52390857 0.88405325 0.86698788]
 [0.66922468 0.68627727 0.15663    0.70034775]
 [0.89452827 0.49829612 0.56598308 0.49894366]
 [0.32152873 0.58211177 0.42358484 0.62505722]]


In [3]:
#shape te indica número de filas y columnas o dimensiones de una matriz
print(a.shape)

(10, 4)


In [4]:
#shape te da el número de elementos de la array
print(a.size)

40


In [6]:
#crea un array con 2 grupos de 3 matrices 4x5
c = np.random.random((2,3,4,5))
print(c)

[[[[0.59659429 0.19437503 0.01045141 0.67173172 0.28426499]
   [0.84899785 0.3988092  0.66117957 0.31891461 0.44075306]
   [0.44651241 0.23291283 0.73703552 0.30280668 0.94021493]
   [0.76488975 0.18170574 0.42506337 0.61746555 0.0343718 ]]

  [[0.11463796 0.70643529 0.06298917 0.23427709 0.63405063]
   [0.33897572 0.5184202  0.23225317 0.74629892 0.39682031]
   [0.58069289 0.13569149 0.05968902 0.22064856 0.44856716]
   [0.30457476 0.89887943 0.72571557 0.98714977 0.56495688]]

  [[0.51575919 0.14163142 0.71997029 0.36260298 0.62757395]
   [0.80809895 0.36986743 0.86908112 0.41365164 0.37894753]
   [0.96258956 0.76007162 0.79255982 0.90633883 0.74724954]
   [0.26565125 0.72071467 0.27437234 0.36067161 0.14320611]]]


 [[[0.69132052 0.01347766 0.08787916 0.07538714 0.13473036]
   [0.14606188 0.01707382 0.34174667 0.66966187 0.79048198]
   [0.26771485 0.91725498 0.77606149 0.38493565 0.57814368]
   [0.88046198 0.54739545 0.26561461 0.83373182 0.60852199]]

  [[0.04601678 0.41229712 0.53

In [7]:
#primer grupo del array C
print(c[0])

[[[0.59659429 0.19437503 0.01045141 0.67173172 0.28426499]
  [0.84899785 0.3988092  0.66117957 0.31891461 0.44075306]
  [0.44651241 0.23291283 0.73703552 0.30280668 0.94021493]
  [0.76488975 0.18170574 0.42506337 0.61746555 0.0343718 ]]

 [[0.11463796 0.70643529 0.06298917 0.23427709 0.63405063]
  [0.33897572 0.5184202  0.23225317 0.74629892 0.39682031]
  [0.58069289 0.13569149 0.05968902 0.22064856 0.44856716]
  [0.30457476 0.89887943 0.72571557 0.98714977 0.56495688]]

 [[0.51575919 0.14163142 0.71997029 0.36260298 0.62757395]
  [0.80809895 0.36986743 0.86908112 0.41365164 0.37894753]
  [0.96258956 0.76007162 0.79255982 0.90633883 0.74724954]
  [0.26565125 0.72071467 0.27437234 0.36067161 0.14320611]]]


In [9]:
#segundo subgrupo del primer grupo
print(c[0,1])

[[0.11463796 0.70643529 0.06298917 0.23427709 0.63405063]
 [0.33897572 0.5184202  0.23225317 0.74629892 0.39682031]
 [0.58069289 0.13569149 0.05968902 0.22064856 0.44856716]
 [0.30457476 0.89887943 0.72571557 0.98714977 0.56495688]]


In [10]:
#cuarta columna del segundo subgrupo
print(c[0,1,:,3])

[0.23427709 0.74629892 0.22064856 0.98714977]


In [11]:
#valor de la tercera fila y la cuarta columna del segundo subgrupo
print(c[0,1,2,3])

0.2206485625227973


### Convert data structures to arrays

In [ ]:
### why? it makes it easier to operate with numpy

In [14]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# axis = 0 son columnas
# axis = 1 son filas

In [15]:
print(np.sum(a))

24.09238605316083


In [17]:
print(np.sum(a, axis=1))

[1.98087272 2.99728142 2.557233   2.60561972 2.7247643  1.38471469
 3.21938681 2.2124797  2.45775112 1.95228256]


## Práctica en clase

In [20]:
numbers = [1,2,3,4,5]

In [26]:
strings = ["uno", "dos", "tres"]

In [48]:
def suma(lst):
    suma = 0
    for i in lst:
        if type(i) == int:
            suma += i
        else:
            print("Error")

In [31]:
suma(numbers)

15

In [32]:
suma(strings)

TypeError: unsupported operand type(s) for +=: 'int' and 'str'

In [34]:
a = np.array(numbers)

In [35]:
a[0]

1

In [36]:
#cambiar el valor de uno a dos
a[0] = 2

In [41]:
#el resultado indica que hay 5 de una sola dimensión
np.shape(a)

(5,)

In [43]:
a.shape

(5,)

In [39]:
#suma
np.sum(a)

16

In [40]:
#también se puede hacer:
a.sum()

16

In [44]:
b = np.array([[1,2,3],[4,5,6]])

In [46]:
print(b.shape)

(2, 3)


In [47]:
print(b[0,0], b[0,1],b[1,0])

1 2 4


In [ ]:
#función que el parámetro de la función es una lista de números. usar la función de numpy para sumar un array para sumar una lista

In [51]:
def calculator(list_of_numbers):
    result = np.array(list_of_numbers).sum()
    print(f'The result is {result}')

In [52]:
calculator(b)

The result is 21


In [53]:
#media de la variable a
a.mean()

3.2

In [54]:
#desviación estándar poblacional de la variable a
a.std()

1.16619037896906

In [60]:
#función que convierte una lista de números en un array. El segundo parámetro es la operación que le quieres aplicar.
def calculator(list_of_numbers, operator):
    result = operator(np.array(list_of_numbers))
    print(f'The result is {result}')

In [61]:
calculator(numbers,sum)

The result is 15


In [63]:
calculator(numbers, np.mean)

The result is 3.0


In [64]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [65]:
#la función también funciona con la matriz de arriba
calculator(matrix,np.sum)

The result is 45


In [67]:
random_matrix = np.random.random([3,3])

In [68]:
random_matrix

array([[0.4971037 , 0.22870231, 0.1253405 ],
       [0.97916132, 0.94929509, 0.62619106],
       [0.72218934, 0.22483208, 0.54378404]])

In [69]:
random_matrix.sum()

4.8965994487494955

In [70]:
#la suma de las columnas
random_matrix.sum(axis=0)

array([2.19845435, 1.40282948, 1.29531561])

In [71]:
#para la suma de las filas
random_matrix.sum(axis=1)

array([0.85114651, 2.55464748, 1.49080546])

In [72]:
#valor medio para las columnas
random_matrix.mean(axis=0)

array([0.73281812, 0.46760983, 0.43177187])

In [74]:
#desviación estándar para las columnas
random_matrix.std(axis=0)

array([0.19694266, 0.34060658, 0.21927588])

In [75]:
#empezar con un array que tiene solo 0
a = np.zeros([2,2])

In [76]:
print(a)

[[0. 0.]
 [0. 0.]]


In [77]:
b = np.ones([2,2])

In [79]:
b

array([[1., 1.],
       [1., 1.]])

In [84]:
h = np.ones([2,2],dtype=np.int64)
h

array([[1, 1],
       [1, 1]])

In [81]:
#generar una matriz con un número fijo
c = np.full((2,2),7)
c

array([[7, 7],
       [7, 7]])

In [82]:
#números espejo
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [85]:
#crear una matrix de 3 x 4

In [87]:
matrix = np.random.random([3,4])
matrix

array([[0.54178797, 0.19271656, 0.60587552, 0.11068918],
       [0.70116816, 0.88461563, 0.66180567, 0.47508314],
       [0.97161372, 0.71002361, 0.11725969, 0.65925769]])

In [91]:
#valores de las dos primeras columnas y dos primeras filas
b = matrix[:2,:2]
b

array([[0.54178797, 0.19271656],
       [0.70116816, 0.88461563]])

In [97]:
mat1 = np.random.random([3,3])
mat2 = np.random.random([3,3])

In [98]:
mat1

array([[0.79436866, 0.97339213, 0.03643343],
       [0.79853503, 0.8279513 , 0.62696743],
       [0.24533127, 0.51236008, 0.65281986]])

In [99]:
mat2

array([[0.25856587, 0.89161188, 0.2758238 ],
       [0.2911334 , 0.51981251, 0.06023839],
       [0.12449758, 0.04125594, 0.96274931]])

In [105]:
#sumar dos matrices
np.add(mat1,mat2)

array([[1.05293453, 1.86500401, 0.31225723],
       [1.08966842, 1.34776381, 0.68720582],
       [0.36982885, 0.55361602, 1.61556916]])

In [106]:
#restar dos matrices
np.subtract(mat1,mat2)

array([[ 0.5358028 ,  0.08178024, -0.23939037],
       [ 0.50740163,  0.30813879,  0.56672904],
       [ 0.12083369,  0.47110414, -0.30992945]])

In [107]:
#dividir dos matrices
np.divide(mat1,mat2)

array([[ 3.0722101 ,  1.0917218 ,  0.13208952],
       [ 2.74284927,  1.59278834, 10.40810441],
       [ 1.97057056, 12.4190628 ,  0.67807876]])

In [108]:
#multiplicar matrices
np.multiply(mat1,mat2)

array([[0.20539662, 0.86788799, 0.01004921],
       [0.23248022, 0.43037944, 0.03776751],
       [0.03054315, 0.0211379 , 0.62850186]])